services:
  msr:
    container_name: msr
    image: stt-hello-world-jdbc
    ports:
      - "15555:5555"
    env_file:
      - .env
    volumes:
      - ./application.properties:/opt/softwareag/IntegrationServer/application.properties
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
